spring:
  application:
    name: Spring Boot ChatBot

  ai:
    openai:
      base-url: https://api.groq.com/openai      
      api-key: ${AI_API_KEY}  
      chat:
        options:
          model: llama-3.3-70b-versatile
          temperature: 0.7

  web:
    cors:
      allowed-origins: "http://localhost:3000"
      allowed-methods: "GET,POST,OPTIONS"
      allowed-headers: "*"

server:
  port: 8080

logging:
  level:
    org.springframework.ai: DEBUG
    org.springframework.web: DEBUG
